// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/release-pipeline/SplitNarrative.tsx": () => import("../components/mockups/release-pipeline/SplitNarrative.tsx"),
  "./components/mockups/release-pipeline/StorytellingFlow.tsx": () => import("../components/mockups/release-pipeline/StorytellingFlow.tsx")
};
